MySystem/ViewModels/SidePage/SidePageViewModel.cs
using System.Collections.Generic;
using System.Data;
using ConnetDB.MySystemDB;
using MySystem.Models.Function;
using System;
using MySystem.Models.Account;
using System.Linq;
using MySystem.Models.Management;
using MySystem.ViewModels.Management;

namespace MySystem.ViewModels.Function
{
    public class SidePageViewModel : ModelBase
    {
        public string Message="";

        /// <summary>
        /// 主功能清單
        /// </summary>
        public List<MainFunctionModel> MainFunctionList = new List<MainFunctionModel>();
        /// <summary>
        /// 子功能清單
        /// </summary>
        public List<SubFunctionViewModel> SubFunctionList = new List<SubFunctionViewModel>();
        /// <summary>
        /// 取得主功能清單
        /// </summary>
        public void getMainFunctionList()
        { 
            MainFunctionDB mainfunctionDB = new MainFunctionDB();
            DataTable MainFunctionDT = new DataTable();
            MainFunctionDT = mainfunctionDB.getData();
            foreach (DataRow dr in MainFunctionDT.Rows)
            {
                MainFunctionModel Data = new MainFunctionModel();
                Data.MainFunctionID = Convert.ToInt32(dr["MainFunctionID"]);
                Data.MainFunctionName = dr["MainFunctionName"].ToString();
                MainFunctionList.Add(Data);
            }
        }
        //取得子功能清單
        public string getSubFunctionList()
        {
            SubFunctionDB subfunctionDB = new SubFunctionDB();
            DataTable MainFunctionDT = new DataTable();
            MainFunctionDT = subfunctionDB.getData();
            if (CheckDataTableIsError(MainFunctionDT))
            {
                return MainFunctionDT.Rows[0]["msg"].ToString();
            }
            foreach (DataRow dr in MainFunctionDT.Rows)
            {
                SubFunctionViewModel Data = new SubFunctionViewModel();
                Data.SubFunctionID = dr["SubFunctionID"].ToString();
                Data.SubFunctionENName = dr["SubFunctionENName"].ToString();
                Data.SubFunctionCNName = dr["SubFunctionCNName"].ToString();
                Data.SubFunctionURL = dr["SubFunctionURL"].ToString();
                Data.MainFunctionType = Convert.ToInt32(dr["MainFunctionType"]);
                SubFunctionList.Add(Data);
            }

            return null;
        }
    }
}

MySystem/Controllers/BasePage/SidePageController.cs
using MySystem.ViewModels.Function;
using System.Web.Mvc;

namespace MySystem.Controllers
{
    public class SidePageController : Controller
    {
        //
        // GET: /SidePage/

        public ActionResult _SidePage()
        {
            SidePageViewModel model = new SidePageViewModel();
            string message = string.Empty;
            model.getMainFunctionList();
            message =  model.getSubFunctionList();
            return View(model);
        }

    }
}

MySystem/Controllers/SidePage/SidePageController.cs
using MySystem.ViewModels.Function;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MySystem.Controllers
{
    public class SidePageController : Controller
    {
        //
        // GET: /SidePage/

        public ActionResult _SidePage()
        {
            SidePageViewModel model = new SidePageViewModel();
            string message = string.Empty;
            model.getMainFunctionList();
            message =  model.getSubFunctionList();
            return View(model);
        }

    }
}

MySystem/Views/Shared/_HeadPage.cshtml
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Portfolio</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Gallery</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="~/Account/LogInPage"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            </ul>
        </div>
    </div>
</nav>

MySystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
    
    /* Remove the navbar's default margin-bottom and rounded borders */
    .navbar {
        margin-bottom: 0;
        border-radius: 0;
    }

    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}

    /* Set gray background color and 100% height */
    .sidenav {
        padding-top: 20px;
        background-color: #f1f1f1;
        height: 100%;
    }

    /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }
</style>
</head>
<body>
    <header>
        @Html.Partial("_HeadPage")
    </header>
    <div class="container-fluid">
        <div class="row content">
            <div class="col-lg-2 sidenav">
                @{Html.RenderAction("_SidePage", "SidePage");}
                @*tml.Partial("_SidePage")*@
            </div>
            <div class="col-md-10">
                    <div class="page-header">
                        <h1>
                            @ViewBag.Title
                        </h1>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <!-- Contents -->
                            @RenderBody()
                        </div>
                    </div>
                </div>
        </div>
    </div>
        @*<footer class="container-fluid text-center">
            <p>Footer Text</p>
        </footer>*@
        <!-- Scripts -->
     <script src="/Scripts/jquery-3.2.1.js"></script>
     <script src="~/Scripts/bootstrap.js"></script>
</body>

</html>

MySystem/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewBag.Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 450px;
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }
    </style>
</head>
<body>
    <header>
        @Html.Partial("_HeadPage")
    </header>
    <!-- Contents -->
    <div class="container-fluid">
        <div class="row content">
            @RenderBody()
        </div>
    </div>
    <footer class="container-fluid text-center">
        <p>Footer Text</p>
    </footer> 
    <!-- Scripts -->
    <script src="~/Scripts/jquery-3.2.1.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
</body>
</html>

MySystem/Views/Shared/_SidePage.cshtml
@model MySystem.ViewModels.Function.SidePageViewModel
@{
    Layout = null;
}
<h4>項目清單</h4>
<div class="panel-group">
    <div class="panel panel-default">
        @if (Model.MainFunctionList.Count() > 0)
        { 
          foreach(var data in Model.MainFunctionList)
          { 
             <div class="panel-heading">
                 <h4 class="panel-title">
                     <a data-toggle="collapse" href="#@data.MainFunctionName">@data.MainFunctionName</a>
                 </h4>
             </div>
             <div id=@data.MainFunctionName class="panel-collapse collapse">
                 @foreach(var subdata in Model.SubFunctionList.Where(x=> x.MainFunctionType == data.MainFunctionID))
                 {
                   <ul class="list-group">
                       <li class="list-group-item"><a href=@subdata.SubFunctionURL>@subdata.SubFunctionCNName</a></li>
                   </ul>
                 }
             </div>
          }
        }
    </div>
</div>
@*<div class="input-group">
    <input type="text" class="form-control" placeholder="Search Blog..">
    <span class="input-group-btn">
        <button class="btn btn-default" type="button">
            <span class="glyphicon glyphicon-search"></span>
        </button>
    </span>
</div>*@