MySystem/Models/LikeWeb/WebDataModel.cs
using AutoMapper;
using MySystem.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Web.Mvc;

namespace MySystem.Models.LikeWeb
{
    public class WebDataModel
        
    { 
        /// <summary>
        /// 網頁ID
        /// </summary>
        public string WebID { get; set; }
        /// <summary>
        /// 網頁名稱
        /// </summary>
        public string WebName { get; set; }
        /// <summary>
        /// 網頁類型
        /// </summary>
        public string WebTypeNeme { get; set; }
        /// <summary>
        /// 網址
        /// </summary>
        public string WebURL { get; set; }
    }
}

MySystem/Models/LikeWeb/WebTypeDataDB.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;

namespace MySystem.Models
{
    public class WebTypeDataDB:DbContext
    {
        private string ConnetStr = "Data Source=WIN-2ECGC9BV1OA;Initial Catalog=MySystemManagement;Integrated Security=True;Connect Timeout=15;Encrypt=False;TrustServerCertificate=False";
        private string Message = "";

        //類別ID
        public string WebTypeID{get;set;}
        //類別英文名稱
        public string WebTypeENName{get;set;}
        //類別中文名稱
        public string WebTypeCNName { get; set; }


        public DataTable getWebType()
        {
            SqlConnection myConn = new SqlConnection(ConnetStr);
            DataTable dt = new DataTable();
            string sql = "SELECT * FROM WebTypeData";
            SqlCommand cmd = new SqlCommand(sql, myConn);
            try
            {
                SqlDataAdapter da = new SqlDataAdapter(cmd);
                da.Fill(dt);
                return dt;
            }
            catch (Exception ex)
            {
                Message = ex.ToString();
                return dt;
            }
            finally
            {
                cmd.Cancel();
                myConn.Close();
                myConn.Dispose();
            }

        }
    }
}

MySystem/ViewModels/LikeWeb/WebDataViewModel.cs
using AutoMapper;
using ConnetDB.MySystemDB;
using MySystem.Models;
using MySystem.Models.LikeWeb;
using System;
using System.Collections.Generic;
using System.Data;
using System.Web.Mvc;

namespace MySystem.ViewModels.LikeWeb
{
    public class WebDataViewModel
        
    { 
        #region  連接DB用
        //呼叫WebDataDB
        WebDataDB _WebDataDB = new WebDataDB();
        //呼叫WebTypeDataDB
        WebTypeDataDB _WebTypeDataDB = new WebTypeDataDB();
        #endregion

        /// <summary>
        /// 網頁名稱
        /// </summary>
        public string WebName { get; set; }
        /// <summary>
        /// 網頁類型
        /// </summary>
        public string WebTypeNeme { get; set; }
        /// <summary>
        /// 網址
        /// </summary>
        public string WebURL { get; set; }
        /// <summary>
        /// 儲存網業類清單
        /// </summary>
        public IEnumerable<SelectListItem> _WebTypeList { get; set; }
        /// <summary>
        /// 儲存我的最愛網頁資訊
        /// </summary>
        public List<WebDataModel> WebDataList = new List<WebDataModel>();
        /// <summary>
        /// 儲存錯誤訊息
        /// </summary>
        public string Message;
        class dda
        {
            public string WebID { get; set; }
            public string WebName { get; set; }
            public string WebType { get; set; }
            public string WebURL { get; set; }
        }
        
        public void getWebdataDB()
        {
            try
            {
                DataTable dt = _WebDataDB.getWebdata();

                foreach (DataRow dr in dt.Rows)
                {
                    WebDataModel wdm = new WebDataModel();
                    wdm.WebID = dr["WebID"].ToString();
                    wdm.WebName = dr["WebName"].ToString();
                    wdm.WebTypeNeme = dr["WebType"].ToString();
                    wdm.WebURL = dr["WebURL"].ToString();
                    WebDataList.Add(wdm);
                }
            }
            catch(Exception ex)
            {
                Message = ex.StackTrace.ToString();
            }
        }

        public void getWebType()
        {
            DataTable dt = _WebTypeDataDB.getWebType();
            List<SelectListItem> mySelectItemList = new List<SelectListItem>();
            try
            {
                foreach (DataRow dr in dt.Rows)
                {
                    mySelectItemList.Add(new SelectListItem()
                    {
                        Text = dr["WebTypeCNName"].ToString(),
                        Value = dr["WebTypeID"].ToString(),
                        Selected = false
                    });
                }
                _WebTypeList = mySelectItemList;
            }
            catch(Exception ex)
            {
                Message = ex.StackTrace.ToString();
            }
        }

        public string addWebdataDB(string WebName, string WebType, string WebURL)
        {

            Message = _WebDataDB.addWebdata(WebName, WebType, WebURL);
            if (string.IsNullOrEmpty(Message))
            { 
            
            }
            return null;
        }


    }
}

MySystem/Controllers/LikeWeb/LikeWebController.cs
using MySystem.ViewModels.LikeWeb;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Linq;
using MySystem.Models.LikeWeb;
using ConnetDB.MySystemDB;

namespace MySystem.Controllers
{
    public class LikeWebController : Controller
    {
        //
        // GET: /LikeWeb/
        public ActionResult LikeWebMainPage()
        {
            WebDataViewModel model = new WebDataViewModel();
            

            model.getWebdataDB();
            if (!string.IsNullOrEmpty(model.Message))
            {
                return View(model);
            }
            model.getWebType();
            if (!string.IsNullOrEmpty(model.Message))
            {
                return View(model);
            }
            Session["WebDataList"] = model.WebDataList;

            return View(model);
        }
        public JsonResult LikeWebMainPage1()
        {
            WebDataViewModel model = new WebDataViewModel();
            model.getWebdataDB();

            return Json(model.WebDataList, "success");
        }
        #region 新增頁面
        public ActionResult LikeWebAddPage()
        {
            WebDataViewModel model = new WebDataViewModel();
            model.getWebType();
            if (!string.IsNullOrEmpty(model.Message))
            {
                return null;
            }
            return View(model);
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult LikeWebAddPage(WebDataViewModel model)
        {
            /*WebDataDB model = new WebDataDB();
            if (!string.IsNullOrEmpty(WebName) || !string.IsNullOrEmpty(WebType) || !string.IsNullOrEmpty(WebURL))
            {
                string ErrorMessage = "";
                model.WebName = WebName;
                model.WebType = WebType;
                model.WebURL = WebURL;
                //ErrorMessage = model.addWebdataDB(WebName, WebType, WebURL);
            }*/
            return new RedirectResult("/LikeWeb/LikeWebMainPage");
        }
        #endregion

        #region 修改頁面
        public ActionResult LikeWebModifyPage(string WebName)
        {
            ViewBag.Title = "編輯頁面";
            WebDataViewModel model = new WebDataViewModel();
            model.WebDataList = Session["WebDataList"] as List<WebDataModel>;
            model.getWebType();
            if (!string.IsNullOrEmpty(model.Message))
            {
                return View(model);
            }
            WebDataModel SelectData = new WebDataModel();
            SelectData = model.WebDataList.Where(x => x.WebName == WebName).FirstOrDefault();
            model.WebName = SelectData.WebName;
            model.WebTypeNeme = SelectData.WebTypeNeme;
            model.WebURL = SelectData.WebURL;
            return View(model);
        }
        [HttpPost]
        public ActionResult LikeWebModifyPage(WebDataDB model)
        {

            return new RedirectResult("/LikeWeb/LikeWebMainPage");
        }
        #endregion
    }
}

MySystem/Views/LikeWeb/LikeWebAddPage.cshtml
@model MySystem.ViewModels.LikeWeb.WebDataViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    
}
    <h2>新增我的最愛網頁</h2>
    <!-- Contents -->
    @using (Html.BeginForm("LikeWebAddPage", "LikeWeb", FormMethod.Post))
    {
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-heading">請輸入網站資訊</div>
                <div class="panel-body">
                    <div class="form-group row">
                        <div class="col-xs-3">
                            <label class="control-label"><a class="text-warning">*</a>網頁名稱:</label>
                            @Html.TextBoxFor(m => m.WebName, new { @class = "form-control", placeholder = "Enter WebName" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-xs-3">
                            <label class="control-label"><a class="text-warning">*</a>網頁類型:</label>
                            @Html.DropDownListFor(m => m.WebTypeNeme, Model._WebTypeList, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-xs-8">
                            <label class="control-label">網頁連結:</label>
                            @Html.TextBoxFor(m => m.WebURL, new { @class = "form-control", placeholder = "Enter WebURL" })
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <button class="btn btn-success" type="submit" onclick="return confirm('確定要新增嗎?');">
                        <span class="glyphicon glyphicon-ok-circle"></span> 確定新增
                    </button>
                </div>
            </div>
        </div>
    }

MySystem/Views/LikeWeb/LikeWebMainPage.cshtml
@model MySystem.ViewModels.LikeWeb.WebDataViewModel

@{
    ViewBag.Title = "我的最愛網頁管理頁面";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
 <div class="row col-md-10 col-md-offset-1">
        <div class="panel panel-default">
            <div class="panel-heading">
                <table>
                    <tr>
                        <td>
                            <div class="dropdown">
                                @Html.DropDownListFor(m => m.WebTypeNeme, Model._WebTypeList, new { @class = "form-control" })
                            </div>
                        </td>
                        <td>
                            <input type="text" class="form-control " placeholder="Search" name="search">
                        </td>
                        <td>
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                            </div>
                        </td>
                        <td><button type="button" class="btn" onclick="location.href ='LikeWebAddPage'">新增我的最愛網頁</button></td>
                    </tr>
                </table>
            </div>
            <div class="panel-body">
                    <!-- Contents -->
                    <table class="table table-hover">
                        <thead>
                            <tr class="success">
                                <th>網頁名稱</th>
                                <th>網頁類型</th>
                                <th>網頁連結</th>
                                <th>動作</th>
                            </tr>
                        </thead>
                        <tbody id="tbTeams">
                            @foreach (var data in Model.WebDataList)
                            {
                                <tr>
                                    <td>@data.WebName</td>
                                    <td>@data.WebTypeNeme</td>
                                    <td><a href=@data.WebURL>@data.WebURL</a></td>
                                    <td><button type="button" class="btn" onclick="location.href = 'LikeWebModifyPage?WebName=@data.WebName'">修改</button></td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
        </div>
</div>

MySystem/Views/LikeWeb/LikeWebModifyPage.cshtml
@model MySystem.ViewModels.LikeWeb.WebDataViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<html>
<body>
    <!-- Contents -->

    <form class="form-horizontal">
        @using (Html.BeginForm("LikeWebModifyPage", "LikeWeb", FormMethod.Post))
        {
        <table class="table table-hover">
            <thead>
                <tr><td><p>@ViewBag.Title<p></td></tr>
            </thead>
            <tbody>
                    <tr>
                        <td>
                            <label>網頁名稱</label>
                        </td>
                        <td>
                            @Model.WebName
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label>網頁類型</label>
                        </td>
                        <td>
                            <div class="dropdown">
                                @Html.DropDownListFor(m => m.WebTypeNeme, Model._WebTypeList, new { @class = "form-control" })
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label>網頁連結</label>
                        </td>
                        <td>
                            @Html.TextBoxFor(model => model.WebURL, new { style = " width:400px;" })
                        </td>
                    </tr>
                
            <tbody>
        </table>
        <button type="submit" class="btn btn-success">確定</button>
        }
     </form>
</body>

</html>