MySystem/Models/Management/CalendarModel.cs
using ConnetDB.MySystemDB;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MySystem.Models.Function
{
    public class CalendarModel
    {
        [Display(Name = "ID")]
        public Int64 ID { get; set; }

        [Display(Name = "EventName")]
        public String EventName { get; set; }

        [Display(Name = "Description")]
        public String Description { get; set; }

        [Display(Name = "EventTime")]
        public DateTime EventTime { get; set; }

        [Display(Name = "CreateDate")]
        public DateTime CreateDate { get; set; }  
    }
}

MySystem/Models/Management/MainFunctionModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MySystem.Models.Management
{
    public class MainFunctionModel
    {
        /// <summary>
        /// 功能代號
        /// </summary>
        public int MainFunctionID { get; set; }
        /// <summary>
        /// 功能名稱
        /// </summary>
        public string MainFunctionName { get; set; }
    }
}

MySystem/ViewModels/Management/CalendarViewModel.cs
using ConnetDB.MySystemDB;
using MySystem.Models;
using MySystem.Models.Function;
using MySystem.ViewModels.Public;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;

namespace MySystem.ViewModels.Management
{
    public class CalendarViewModel:Model_Base
    {
        public string Active { get; set; }
        public Int64  ID{ get; set; }
        public String EventName { get; set; }
        public String Description { get; set; }
        public String EventTime { get; set; }

        #region DB
        TB_Calendar_DB calendarDB;
        #endregion

        #region List
        public List<CalendarModel> CalendarList;
        #endregion

        public void init()
        {
            this.EventTime = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss");
        }

        public string addCalendar()
        {
            DateTime Now = DateTime.Now;
            sqlParameter = new SQLParameter();
            sqlParameter.SetActionValue.Add("EventName", this.EventName);
            sqlParameter.SetActionValue.Add("Description", this.Description);
            sqlParameter.SetActionValue.Add("EventTime", this.EventTime);
            sqlParameter.SetActionValue.Add("CreateDate", Now);
            calendarDB = new TB_Calendar_DB();
            return calendarDB.addData(sqlParameter);
        }

        public string editCalendar(string MainFunctionName)
        {
            sqlParameter = new SQLParameter();
            sqlParameter.SetActionValue.Add("MainFunctionName", MainFunctionName);
            calendarDB = new TB_Calendar_DB();
            return calendarDB.editData(sqlParameter);
        }

        public string deleteCalendar(string ID)
        {
            sqlParameter = new SQLParameter();
            sqlParameter.WhereCondition.Add("ID", ID);
            calendarDB = new TB_Calendar_DB();
            return calendarDB.deleteDate(sqlParameter);
        }

        #region 取得主功能清單
        public string getCalendar()
        {
            sqlParameter = new SQLParameter();
            sqlParameter.OrderByValue = "EventTime Desc";
            calendarDB = new TB_Calendar_DB();
            DataTable dt = calendarDB.getData(sqlParameter);
            if (CheckDataTableExist(dt) == false)
                return "查無資料!";
            CalendarList = new List<CalendarModel>();
            CalendarList = (DataTableConvertToList.ToList<CalendarModel>(dt));
            sqlParameter = null;
            return null;
        }
        #endregion
    }
}

MySystem/ViewModels/Management/FunctionTypeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MySystem.ViewModels.Management
{
    public class FunctionTypeViewModel
    {
        /// <summary>
        /// 功能類別代號
        /// </summary>
        public string FunctionTypeID { get; set; }
        /// <summary>
        /// 功能類別英文名稱
        /// </summary>
        public string FunctionTypeENName { get; set; }
        /// <summary>
        /// 功能類別中文名稱
        /// </summary>
        public string FunctionTypeCNName { get; set; } 
    }
}

MySystem/ViewModels/Management/MainFunctionViewModel.cs
using ConnetDB.MySystemDB;
using MySystem.Models;
using MySystem.Models.Management;
using MySystem.ViewModels.Public;
using System;
using System.Collections.Generic;
using System.Data;
using System.Web.Mvc;

namespace MySystem.ViewModels.Management
{
    public class MainFunctionViewModel:Model_Base
    {
        public string Select_FunctionType { get; set; }
        /// <summary>
        /// 功能代號
        /// </summary>
        public int MainFunctionID { get; set; }
        /// <summary>
        /// 功能名稱
        /// </summary>
        public string MainFunctionName { get; set; }
        public string EditName { get; set; }

        public string Active { get; set; }

        #region 連接DB
        /// <summary>
        /// MainFunctionDB
        /// </summary>
        MainFunctionDB mainfunctionDB = new MainFunctionDB();
        SubFunctionDB subfunctionDB = new SubFunctionDB();
        #endregion

        public List<MainFunctionModel> MainFunctionList = new List<MainFunctionModel>();

        /// <summary>
        /// 儲存網頁類清單
        /// </summary>
        public IEnumerable<SelectListItem> Function_Select 
        { 
            get
            {
              List<SelectListItem> mySelectItemList = new List<SelectListItem>();
              mySelectItemList.Add(new SelectListItem() { Text = "主功能", Value = "0" });
              mySelectItemList.Add(new SelectListItem() { Text = "子功能", Value = "1" });
              if (!string.IsNullOrEmpty(Select_FunctionType))
              {
                  Select_FunctionType = "0";
              }
              return mySelectItemList;
            }
        }

        public string addMainFunction(string MainFunctionName)
        {
            sqlParameter = new SQLParameter();
            sqlParameter.SetActionValue.Add("MainFunctionName", MainFunctionName);
            return mainfunctionDB.addData(sqlParameter);
        }

        public string editMainFunction(string MainFunctionID)
        {
            sqlParameter = new SQLParameter();
            sqlParameter.SetActionValue.Add("MainFunctionName", this.MainFunctionName);
            sqlParameter.WhereCondition.Add("MainFunctionName", MainFunctionID);
            return mainfunctionDB.editData(sqlParameter);
        }

        public string deleteMainFunction()
        {
            sqlParameter = new SQLParameter();
            sqlParameter.WhereCondition.Add("MainFunctionID", MainFunctionID.ToString());
            return mainfunctionDB.deleteDate(sqlParameter);
        }

        #region 取得主功能清單
        public string getMainFunction()
        {
            sqlParameter = new SQLParameter();
            sqlParameter.OrderByValue = "MainFunctionID";
            DataTable dt = mainfunctionDB.getData(sqlParameter);
            if (CheckDataTableExist(dt) == false)
                return "查無資料!";
            MainFunctionList = (DataTableConvertToList.ToList<MainFunctionModel>(dt));
            sqlParameter = null;
            return null;
        }
        #endregion

        #region 取得子功能清單
        public string getSubFunction()
        {
            sqlParameter = new SQLParameter();
            sqlParameter.OrderByValue = "SubFunctionID";
            DataTable dt = subfunctionDB.getData(sqlParameter);
            if (CheckDataTableExist(dt) == false)
                return "查無資料!";
            MainFunctionList = (DataTableConvertToList.ToList<MainFunctionModel>(dt));
            sqlParameter = null;
            return null;
        }
        #endregion

        

    }
}

MySystem/ViewModels/Management/SubFunctionViewModel.cs
using ConnetDB.MySystemDB;
using MySystem.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MySystem.ViewModels.Management
{
    
    public class SubFunctionViewModel
    {
        /// <summary>
        /// 功能代號
        /// </summary>
        public string SubFunctionID { get; set; }
        /// <summary>
        /// 功能英文名稱
        /// </summary>
        public string SubFunctionENName { get; set; }
        /// <summary>
        /// 功能中文名稱
        /// </summary>
        public string SubFunctionCNName { get; set; }
        /// <summary>
        /// 功能連結地址
        /// </summary>
        public string SubFunctionURL { get; set; }
        /// <summary>
        /// 功能類別
        /// </summary>
        public int MainFunctionType { get; set; }

        //呼叫WebTypeDataDB
        MainFunctionDB mainfunctionDB;
        SubFunctionDB subfunctionDB;
        /// <summary>
        /// 儲存網業類清單
        /// </summary>
        public IEnumerable<SelectListItem> _MainFunctionList { get; set; }
        public string get_MainFunctionList()
        {
            mainfunctionDB = new MainFunctionDB();
            DataTable dt = mainfunctionDB.getData();
            List<SelectListItem> mySelectItemList = new List<SelectListItem>();
            try
            {
                foreach (DataRow dr in dt.Rows)
                {
                    mySelectItemList.Add(new SelectListItem()
                    {
                        Text = dr["MainFunctionName"].ToString(),
                        Value = dr["MainFunctionID"].ToString(),
                        Selected = false
                    });
                }
                _MainFunctionList = mySelectItemList;
            }
            catch (Exception ex)
            {
                return ex.StackTrace.ToString();
            }
            return null;
        }

        public string addSubFunction()
        {
            subfunctionDB = new SubFunctionDB();
            string addSubFunctionMessage = subfunctionDB.addSubFunction(SubFunctionENName, SubFunctionCNName, SubFunctionURL, MainFunctionType);
            return addSubFunctionMessage;
        }
    }
}

MySystem/Controllers/Management/FunctionController.cs
using MySystem.ViewModels.Management;
using System;
using System.Web.Mvc;

namespace MySystem.Controllers
{
    public class FunctionController : Controller
    {
        //
        // GET: /Function/

        public ActionResult MainFunctionAddPage()
        {
            MainFunctionViewModel model = new MainFunctionViewModel();
            string message = String.Empty;
            return View(model);
        }
        [HttpPost]
        public ActionResult MainFunctionAddPage(MainFunctionViewModel model)
        {
            string message = String.Empty;
            message = model.addMainFunction(model.MainFunctionName);
            return RedirectToAction("MainFunctionPage");
        }

        public ActionResult MainFunctionPage()
        {
            ViewBag.Title = "功能清單";
            MainFunctionViewModel model = new MainFunctionViewModel();
            model.getMainFunction();
            string message = String.Empty;
            return View(model);
        }
        [HttpPost]
        public ActionResult MainFunctionPage(MainFunctionViewModel model)
        {
            string message = String.Empty;
            if (model.Active == "Add")
            {
                message = model.addMainFunction(model.MainFunctionName);
            }
            if (model.Active != null && model.Active.IndexOf("Edit")>=0)
            {
                message = model.editMainFunction(model.Active.Split(',')[1]);
            }
            if (model.Active == "Delete")
            {
                message = model.deleteMainFunction();
            }
            //return View(model);
            return RedirectToAction("MainFunctionPage");
        }
        public ActionResult SubFunctionAddPage()
        {
            SubFunctionViewModel model = new SubFunctionViewModel();
            string message = String.Empty;
            message = model.get_MainFunctionList(); //取得網業類型
            return View(model);
        }
        [HttpPost]
        public ActionResult SubFunctionAddPage(SubFunctionViewModel model)
        {
            string message = String.Empty;
            model.addSubFunction();
            return RedirectToAction("SubFunctionAddPage");
        }
        public ActionResult FunctionTypeAddPage()
        {
            FunctionTypeViewModel model = new FunctionTypeViewModel();
            
            return View(model);
        }

    }
}

MySystem/Controllers/Management/ManagementController.cs
using MySystem.ViewModels.Management;
using System;
using System.Web.Mvc;

namespace MySystem.Controllers
{
    public class ManagementController : Controller
    {
        public ActionResult CalendarPage()
        {
            ViewBag.Title = "行事表";
            CalendarViewModel model = new CalendarViewModel();
            model.init();
            model.getCalendar();
            string message = String.Empty;
            return View(model);
        }
        
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CalendarPage(CalendarViewModel model)
        {
            string message = String.Empty;
            if (model.Active == "Add")
            {
                message = model.addCalendar();
            }
            if (model.Active!=null &&  model.Active.IndexOf("Edit") >= 0)
            {
                //message = model.editCalendar(model.Active.Split(',')[1]);
            }
            if (model.Active != null && model.Active.IndexOf("Delete") >= 0)
            {
                message = model.deleteCalendar(model.Active.Split(',')[1]);
            }
            return RedirectToAction("CalendarPage");
        }
    }
}

MySystem/Views/Management/CalendarPage.cshtml
@model MySystem.ViewModels.Management.CalendarViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/bootstrap-datetimepicker.min.css" rel="stylesheet" />
<script src="~/Scripts/moment.js"></script>
<script src="~/Scripts/bootstrap-datetimepicker.js"></script>
<script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
<div class="row col-md-12">
    <div class="panel panel-default">
        <div class="panel-body">
            <!-- Contents -->
            <div class="col-md-12">
                @*@using (Html.BeginForm("CalendarPage", "Management", FormMethod.Post))
                {
                    <div class="btn-group">
                        @Html.DropDownListFor(m => m.Select_FunctionType, Model.Function_Select, new { @class = "form-control", onchange = "this.form.submit();" })
                    </div>
                }*@
                <br><br>
                <table class="table table-hover table-bordered table-condensed">
                    <thead>
                        <tr class="info">
                            <th>事件時間</th>
                            <th>事件名稱</th>
                            <th>詳細內容</th>
                            <th>
                                <button id="CreatBtn" type="button" onclick="hide_tr()" class="btn btn-success btn-xs">
                                    <span id="CreatIcon" class="glyphicon glyphicon-plus"></span>
                                </button>
                            </th>
                        </tr>
                    </thead>
                    <tbody id="tbTeams">
                        <tr id="CreatTr" style="display:none">
                            @using (Html.BeginForm("CalendarPage", "Management", FormMethod.Post))
                            {
                                <td>
                                    <div class="form-group">
                                        <div class='input-group date' id='datetimepicker1'>
                                            @Html.TextBoxFor(m => m.EventTime, new { @class = "form-control" })
                                            <span class="input-group-addon">
                                                <span class="glyphicon glyphicon-calendar"></span>
                                            </span>
                                        </div>
                                    </div> 
                                </td>
                                <td>@Html.TextBoxFor(m => m.EventName, new { @class = "form-control" })</td>
                                <td>@Html.TextAreaFor(m => m.Description, new { @class = "form-control" })</td>
                                <td>
                                    <button name="Active" type="submit" class="btn btn-success btn-sm" value="Add">新增</button>
                                </td>
                            }
                        </tr>
                        @if (Model.CalendarList != null && Model.CalendarList.Count > 0)
                        {
                            foreach (var data in Model.CalendarList)
                            {
                                using (Html.BeginForm("CalendarPage", "Management", FormMethod.Post))
                                {
                                    string normal = "normal" + data.ID;
                                    string ActionEdit = "ActionEdit" + data.ID;
                                    string UI = "UI" + data.ID;
                                    <tr>
                                        <td style="width:10%">@data.EventTime @Html.Hidden("EventTime", data.EventTime)</td>
                                        <td style="width:auto">
                                            @data.EventName @Html.Hidden("EventName", data.EventName)
                                        </td>
                                        <td style="width:auto">
                                            @data.Description @Html.Hidden("Description", data.Description)
                                        </td>
                                        <td id="@normal" style="width:15%">
                                            <button type="button" class="btn btn-warning btn-sm" onclick="Edit('@data.ID')">編輯</button>
                                            <button name="Active" type="submit" class="btn btn-danger btn-sm" value=@("Delete," + data.ID)>刪除</button>
                                        </td>
                                        <td id="@ActionEdit" style="display:none;width:15%">
                                            <button name="Active" type="submit" class="btn btn-warning btn-sm" value=@("Edit," + data.ID)>確定</button>
                                            <button type="button" class="btn btn-danger btn-sm" onclick="CancelEdit('@data.ID')">取消</button>
                                        </td>
                                    </tr>
                                }
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    $('#EventTime').datetimepicker({
        format:'YYYY/MM/DD HH:mm:ss'
    });
   function hide_tr() {
       var result_style = document.getElementById('CreatTr').style;
       result_style.display = 'table-row';

       var CreatIcon_style = document.getElementById('CreatIcon');
       CreatIcon_style.className = 'glyphicon glyphicon-minus';
       var CreatBtn_style = document.getElementById('CreatBtn');
       CreatBtn_style.onclick = function () {
           show_tr();
       };
   }
   function show_tr() {
       var result_style = document.getElementById('CreatTr').style;
       result_style.display = 'none';
       var CreatBtn_style = document.getElementById('CreatIcon');
       CreatBtn_style.className = 'glyphicon glyphicon-plus';
       var CreatBtn_style = document.getElementById('CreatBtn');
       CreatBtn_style.onclick = function () {
           hide_tr();
       };
   }
   $("#Select_FunctionType").on("change", function () {
       $("form").submit();
   });
   function Change()
   {
       window.location.href = ('@Url.Action("MainFunctionPage", "Function")');
   }
    function Edit(id)
    {
        var ActionEdit = "#ActionEdit" + id;
        var normal = "#normal" + id;
        $(ActionEdit).show();
        $(normal).hide();
    }
    function CancelEdit(id) {
        var ActionEdit = "#ActionEdit" + id;
        var normal = "#normal" + id;
        $(ActionEdit).hide();
        $(normal).show();
    }
</script>